### ISSUE TITLE
BoolWrapper incorrect work with default values

### ISSUE THREAD

**Issue by Footmau** [tobischo/gokeepasslib#45]
_Steps to reproduce:_
- Open DB in **original** KeePass app and select **Edit Group...** from context menu of a group.
- Open **Behaviour** tab and select **Inherit setting from parent** for **Searching entries in this group** property.
- Save DB.
- Open DB using gokeepasslib.
- Save DB using gokeepasslib.
- Open DB in **original** KeePass app and select **Edit Group...** from context menu of the group.
- Open **Behaviour** tab.

_Expected behaviour:_
The **Searching entries in this group** group property value is **Inherit setting from parent**.

_Observed behaviour:_
The **Searching entries in this group** group property value is **Disabled**.

**Comment by tobischo** [comment]
It is hard for `BoolWrapper` to tell what the expected value for no given value is, especially if **original** KeePass, does not feel the need to be explicit.
As per go default, this then takes `false` as the value, which likely causes the property to be disabled.
Without having looked into this in perfect detail, I'd assume that the XML Body from the original file then just does not keep the attribute at all, which results in defaulting to `false`.

The only way of fixing this is somewhat breaking.
Either by changing BoolWrapper to be pointers and omitempty or by changing the BoolWrapper type to be somewhat more complex:

```go
type BoolWrapper struct {
  Value bool
  Valid bool
}
```
instead of
```go
type BoolWrapper bool
```
I am tempted to go with changing the `BoolWrapper` type, but I'd have to look into the implications some more.
