### ISSUE TITLE
Unexpected change of Password after modifying database

### ISSUE THREAD

**Issue by MarErm27** [tobischo/gokeepasslib#55]
Hello, dear Tobischo!
I've meet unecpected password change after modifying database. I read it twice in this code, so it goes like this:
1) First modefying
TI6bhgbk
TI6bhgbk
2) Second modefying
�� �D�
empty
3)Third modefying
empty
empty

Code below:
```go
package main

import (
	"log"
	"os"
	"fmt"
	"github.com/tobischo/gokeepasslib"
	w "github.com/tobischo/gokeepasslib/wrappers"
)
func mkValue(key string, value string) gokeepasslib.ValueData {
	return gokeepasslib.ValueData{Key: key, Value: gokeepasslib.V{Content: value}}
}

func mkProtectedValue(key string, value string) gokeepasslib.ValueData {
	return gokeepasslib.ValueData{
		Key:   key,
		Value: gokeepasslib.V{Content: value, Protected: w.NewBoolWrapper(true)},
	}
}
func createSubGroups(rootGroup *gokeepasslib.Group){
	subGroup := gokeepasslib.NewGroup()
	subGroup.Name = "test1"

	subEntry := gokeepasslib.NewEntry()
	subEntry.Values = append(subEntry.Values, mkValue("Title", "Another password"))
	subEntry.Values = append(subEntry.Values, mkValue("UserName", "johndough"))
	subEntry.Values = append(subEntry.Values, mkProtectedValue("Password", "123456654321"))

	subGroup.Entries = append(subGroup.Entries, subEntry)

	rootGroup.Groups = append(rootGroup.Groups, subGroup)
}

func main() {
	filename := "example-writing.kdbx"
	masterPassword := "123"
	// Read
	file, err := os.Open(filename)
	if err != nil {
		log.Printf("Failed opening file: %+v", err)
		os.Exit(1)
	}
	
	defer file.Close()

	db := gokeepasslib.NewDatabase()
	db.Credentials = gokeepasslib.NewPasswordCredentials(masterPassword)
	err = gokeepasslib.NewDecoder(file).Decode(db)
	if err != nil {
		log.Printf("Decoding file: %+v", err)
		os.Exit(1)
	}
	db.UnlockProtectedEntries()
	entry := db.Content.Root.Groups[0].Groups[0].Entries[0]
	fmt.Println(entry.GetTitle())
	//fmt.Println(entry.GetPassword())
	fmt.Println(entry.GetContent("Password"))

	// Unlock protected entries to handle stream cipher
	db.UnlockProtectedEntries()

	rootGroup := db.Content.Root.Groups[0]

	// Remove `My GMail password` entry from example-writing example
	//rootGroup.Entries = rootGroup.Entries[:0] 
	
	createSubGroups(&rootGroup)
	db.Content.Root.Groups[0] = rootGroup

	// Lock entries using stream cipher
	db.LockProtectedEntries()

	writeFile, err := os.Create(filename)
	if err != nil {
		panic(err)
	}
	defer writeFile.Close()
	// and encode it into the file
	keepassEncoder := gokeepasslib.NewEncoder(writeFile)
	if err := keepassEncoder.Encode(db); err != nil {
		panic(err)
	}
	file2, err := os.Open(filename)
	if err != nil {
		log.Printf("Failed opening file: %+v", err)
		os.Exit(1)
	}
	defer file.Close()

	db2 := gokeepasslib.NewDatabase()
	db2.Credentials = gokeepasslib.NewPasswordCredentials(masterPassword)
	err = gokeepasslib.NewDecoder(file2).Decode(db2)
	if err != nil {
		log.Printf("Decoding file: %+v", err)
		os.Exit(1)
	}
	entry2 := db2.Content.Root.Groups[0].Groups[0].Entries[0]
	fmt.Println(entry2.GetContent("Password"))
}
```

**Comment by tobischo** [comment]
As far as I can tell you are missing `db2.UnlockProtectedEntries()` when reading the file a second time

Also you are calling `db. UnlockProtectedEntries()` twice, which should only be called once

This works for me:
```
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/tobischo/gokeepasslib"
	w "github.com/tobischo/gokeepasslib/wrappers"
)

func mkValue(key string, value string) gokeepasslib.ValueData {
	return gokeepasslib.ValueData{Key: key, Value: gokeepasslib.V{Content: value}}
}

func mkProtectedValue(key string, value string) gokeepasslib.ValueData {
	return gokeepasslib.ValueData{
		Key:   key,
		Value: gokeepasslib.V{Content: value, Protected: w.NewBoolWrapper(true)},
	}
}
func createSubGroups(rootGroup *gokeepasslib.Group) {
	subGroup := gokeepasslib.NewGroup()
	subGroup.Name = "test1"

	subEntry := gokeepasslib.NewEntry()
	subEntry.Values = append(subEntry.Values, mkValue("Title", "Another password"))
	subEntry.Values = append(subEntry.Values, mkValue("UserName", "johndough"))
	subEntry.Values = append(subEntry.Values, mkProtectedValue("Password", "123456654321"))

	subGroup.Entries = append(subGroup.Entries, subEntry)

	rootGroup.Groups = append(rootGroup.Groups, subGroup)
}

func main() {
	filename := "example-writing.kdbx"
	masterPassword := "supersecret"
	// Read
	file, err := os.Open(filename)
	if err != nil {
		log.Printf("Failed opening file: %+v", err)
		os.Exit(1)
	}

	db := gokeepasslib.NewDatabase()
	db.Credentials = gokeepasslib.NewPasswordCredentials(masterPassword)
	err = gokeepasslib.NewDecoder(file).Decode(db)
	if err != nil {
		log.Printf("Decoding file: %+v", err)
		os.Exit(1)
	}
	db.UnlockProtectedEntries()
	entry := db.Content.Root.Groups[0].Groups[0].Entries[0]
	fmt.Println(entry.GetTitle())
	fmt.Println(entry.GetContent("Password"))

	rootGroup := db.Content.Root.Groups[0]

	createSubGroups(&rootGroup)

	// Lock entries using stream cipher
	db.LockProtectedEntries()

	file.Close()

	// Overwrite existing file
	writeFile, err := os.Create(filename)
	if err != nil {
		panic(err)
	}
	// and encode it into the file
	keepassEncoder := gokeepasslib.NewEncoder(writeFile)
	if err := keepassEncoder.Encode(db); err != nil {
		panic(err)
	}
	writeFile.Close()

	// Check that read was ok
	file2, err := os.Open(filename)
	if err != nil {
		log.Printf("Failed opening file: %+v", err)
		os.Exit(1)
	}
	defer file.Close()

	db2 := gokeepasslib.NewDatabase()
	db2.Credentials = gokeepasslib.NewPasswordCredentials(masterPassword)
	err = gokeepasslib.NewDecoder(file2).Decode(db2)
	if err != nil {
		log.Printf("Decoding file: %+v", err)
		os.Exit(1)
	}
	db2.UnlockProtectedEntries()
	entry2 := db2.Content.Root.Groups[0].Groups[0].Entries[0]
	fmt.Println(entry2.GetTitle())
	fmt.Println(entry2.GetContent("Password"))
}
```

**Comment by MarErm27** [comment]
That helped a lot!

**Comment by MarErm27** [comment]
One other unexpected thing is when I import {	
"github.com/tobischo/gokeepasslib/v3"
	w "github.com/tobischo/gokeepasslib/v3/wrappers"
}
it can't find it,
but when I do this:
{
"github.com/tobischo/gokeepasslib"
	w "github.com/tobischo/gokeepasslib/wrappers"
}
it's fine

**Comment by tobischo** [comment]
Which version of go are you using?
Do you have go modules enabled?

**Comment by MarErm27** [comment]
I'm so sorry, I just didn't know what is go modules!
I've just made a new go module and it worked!
Why there is a need of special version of a library for go module? Do other liblraries from github also need to have a special version for go modules?

**Comment by tobischo** [comment]
Probably all of them that have advanced beyond v1

Go did not have a built in concept of library version management built in from the very beginning.
At the start it was just always `go get` everything and if a breaking change was introduced you were out of luck.
In go1.5 vendoring was introduced (basically copy the dependencies into /vendor inside the repo and build from that). This did not work great for dependencies of dependencies though, as a few of them might rely on different major versions and would also make things not work well together.

Not that long ago the go team then came up with the concept of modules for dependency version management (there are other tools which help with that, but this is the official one). There are also a fee very good blog posts by Russ Cox explaining the reasoning behind this approach, which is a little different from other programming languages.
The gist is that semantic versioning was adopted for go (MAJOR.MINOR.PATCH) where only major version changed should introduce breaking changes. Minor and patch versions should only add and fix things, but not change the API. If you have a larger program though, updating something to a new major version would be a potentially big task, that is then hard to review and might take for forever. The idea therefore is that major versions of a dependency should be able to live next to each other in order to allow updating the different parts of the program step by step. Eventually then it would be possible to just phase out the old version. Additionally this allows working with different major versions of dependencies of dependencies.
The versions are managed through tags and the go tool is using those to fetch the desired major version.

If your program is using modules, it can handle this as described. If your program does not, it falls back to just using latest master on go get (at least for now), so the import path without v3 currently refers to the same code in this repo and would be fine. If you update the dependencies though and a new major version with breaking changes was introduced, your program would stop compiling.

In the case of gokeepasslib I was not very experienced with go when I first built it, so the major versions had to be introduced to accommodate those breaking changes.

During the time of phasing over completely towards using modules, you will probably come across multiple libraries that do not yet support it. The go tool can deal with that though and will ensure that you stick with the same commit

**Comment by MarErm27** [comment]
May I ask one more question?
When I open existing database through Keepass user interface and at same time trying to change it with this library I have no errors. Nothing stops me. It is not saying me not now, it is blocked or it is in use. How can I limit the freedom of this action? How can I check if it is opened?

**Comment by tobischo** [comment]
That depends on the operating system you are using and whether the file is open directly on the same operating system or for example through  network directories (NFS, smb, ...)
You could use something like  https://github.com/juju/fslock
Also see https://stackoverflow.com/questions/52986413/how-to-get-an-exclusive-lock-on-a-file-in-go

**Comment by MarErm27** [comment]
May there be a readon why code that you gave to me just stop to work? I mean two days ago it is did 
a creating new groups with func createSubGroups, but now it's just now. I've copied your code again and the database just not changing

**Comment by Footmau** [comment]
@MarErm27 File is used only to load database. After that all changes are sense only internal object memory. You have to implement save database by yourself.

**Comment by MarErm27** [comment]
@Footmau Footmau
I was wondeering if you may be able this code and to check if in new created database name "dat2.kdbx" will be a new subGroup name "test 1". I've just installed a few things and this code stopped adding subGroups. Please

`package main

import (
	"fmt"
	"log"
	"os"
	"bytes"
	"bufio"
	"github.com/tobischo/gokeepasslib"
	w "github.com/tobischo/gokeepasslib/wrappers"

	"github.com/getlantern/deepcopy"
)

func mkValue(key string, value string) gokeepasslib.ValueData {
	return gokeepasslib.ValueData{Key: key, Value: gokeepasslib.V{Content: value}}
}

func mkProtectedValue(key string, value string) gokeepasslib.ValueData {
	return gokeepasslib.ValueData{
		Key:   key,
		Value: gokeepasslib.V{Content: value, Protected: w.NewBoolWrapper(true)},
	}
}
func createSubGroups(rootGroup *gokeepasslib.Group) {
	subGroup := gokeepasslib.NewGroup()
	subGroup.Name = "test1"

	subEntry := gokeepasslib.NewEntry()
	subEntry.Values = append(subEntry.Values, mkValue("Title", "Another password"))
	subEntry.Values = append(subEntry.Values, mkValue("UserName", "johndough"))
	subEntry.Values = append(subEntry.Values, mkProtectedValue("Password", "123456"))
	subGroup.Entries = append(subGroup.Entries, subEntry)
	rootGroup.Groups = append(rootGroup.Groups, subGroup)
}


func SaveDatabase(db **gokeepasslib.Database) []byte {
	//tmpDB := gokeepasslib.NewDatabase(gokeepasslib.WithDatabaseFormattedTime(!*db.Header.IsKdbx4()))
	tmpDB := gokeepasslib.NewDatabase()
	deepcopy.Copy(tmpDB, *db)
	var data bytes.Buffer
	w := bufio.NewWriter(&data)

	tmpDB.LockProtectedEntries()
	keepassEncoder := gokeepasslib.NewEncoder(w)

	if err := keepassEncoder.Encode(tmpDB); err != nil {
		return nil
	}

	w.Flush()
	return data.Bytes()
}

func check(e error) {
    if e != nil {
        panic(e)
    }
}

func main() {
	filename := "example-writing.kdbx"
	masterPassword := "123"
	// Read
	file, err := os.Open(filename)
	if err != nil {
		log.Printf("Failed opening file: %+v", err)
		os.Exit(1)
	}

	db := gokeepasslib.NewDatabase()
	db.Credentials = gokeepasslib.NewPasswordCredentials(masterPassword)
	err = gokeepasslib.NewDecoder(file).Decode(db)
	if err != nil {
		log.Printf("Decoding file: %+v", err)
		os.Exit(1)
	}
	db.UnlockProtectedEntries()
	entry := db.Content.Root.Groups[0].Groups[0].Entries[0]
	fmt.Println(entry.GetTitle())
	fmt.Println(entry.GetContent("Password"))

	rootGroup := db.Content.Root.Groups[0]

	createSubGroups(&rootGroup)

	// Lock entries using stream cipher
	db.LockProtectedEntries()

	file.Close()

	// Overwrite existing file
	writeFile, err := os.Create(filename)
	if err != nil {
		panic(err)
	}
	// and encode it into the file
	keepassEncoder := gokeepasslib.NewEncoder(writeFile)
	if err := keepassEncoder.Encode(db); err != nil {
		panic(err)
	}
	writeFile.Close()

	// Check that read was ok
	file2, err := os.Open(filename)
	if err != nil {
		log.Printf("Failed opening file: %+v", err)
		os.Exit(1)
	}
	defer file.Close()

	dataBytes := SaveDatabase(&db)
	f, err := os.Create("dat2.kdbx")
    check(err)
    defer f.Close()
	n2, err := f.Write(dataBytes)
    check(err)
	fmt.Printf("wrote %d bytes\n", n2)
	

	db2 := gokeepasslib.NewDatabase()
	db2.Credentials = gokeepasslib.NewPasswordCredentials(masterPassword)
	err = gokeepasslib.NewDecoder(file2).Decode(db2)
	if err != nil {
		log.Printf("Decoding file: %+v", err)
		os.Exit(1)
	}
	db2.UnlockProtectedEntries()
	entry2 := db2.Content.Root.Groups[0].Groups[0].Entries[0]
	fmt.Println(entry2.GetTitle())
	fmt.Println(entry2.GetContent("Password"))
}`

**Comment by tobischo** [comment]
You don't need that additional file writing logic.
The encoder is written so that you can directly pass a file as an io.Writer.

As for why it stopped working: 
Your initial code had:
```go
rootGroup := db.Content.Root.Groups[0]
createSubGroups(&rootGroup)
db.Content.Root.Groups[0] = rootGroup
```
Where you assigned the group to a variable.
You then created a pointer to that value directly.
Since `Groups` is a slice of `Group` and not of `*Group`, this new variable in general leads to a different memory address when creating the pointer, compared to when you create a pointer directly from the slice element.
See https://play.golang.org/p/YjKNp6sewnW for example.

Therefore the rootGroup that was passed in and edited was a different one.
Since the capacity of the `rootGroup.Groups` slice had to be extended on `append`, it created a new array and a slice to it. Since the original array was not changed, `db.Content.Root.Groups[0].Groups` was also unchanged, since `rootGroup.Groups` now held a different address. (Slices are pointers to array, also see https://www.geeksforgeeks.org/slices-in-golang/)

The example I passed back in https://github.com/tobischo/gokeepasslib/issues/55#issuecomment-561532416 did not contain `db.Content.Root.Groups[0] = rootGroup` and therefore the supposedly updated database never contained the new group and entry.

Faulty example:
```go
	rootGroup := db.Content.Root.Groups[0]
	createSubGroups(&rootGroup)
```

So the way to make that part work is to either go with
```go
	rootGroup := db.Content.Root.Groups[0]
	createSubGroups(&rootGroup)
	db.Content.Root.Groups[0] = rootGroup
```
to ensure that any updates done on `rootGroup` are part of the db again

or to create a pointer from the value on the slice directly:
```go
	rootGroup := &db.Content.Root.Groups[0]
	createSubGroups(rootGroup)
```

Full example:
```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/tobischo/gokeepasslib"
	w "github.com/tobischo/gokeepasslib/wrappers"
)

func mkValue(key string, value string) gokeepasslib.ValueData {
	return gokeepasslib.ValueData{Key: key, Value: gokeepasslib.V{Content: value}}
}

func mkProtectedValue(key string, value string) gokeepasslib.ValueData {
	return gokeepasslib.ValueData{
		Key:   key,
		Value: gokeepasslib.V{Content: value, Protected: w.NewBoolWrapper(true)},
	}
}
func createSubGroups(rootGroup *gokeepasslib.Group) {
	subGroup := gokeepasslib.NewGroup()
	subGroup.Name = "test1"

	subEntry := gokeepasslib.NewEntry()
	subEntry.Values = append(subEntry.Values, mkValue("Title", "A second password"))
	subEntry.Values = append(subEntry.Values, mkValue("UserName", "johndo2ugh"))
	subEntry.Values = append(subEntry.Values, mkProtectedValue("Password", "123456"))
	subGroup.Entries = append(subGroup.Entries, subEntry)
	rootGroup.Groups = append(rootGroup.Groups, subGroup)
}

func main() {
	filename := "example-writing.kdbx"
	targetFilename := "example-with-data.kdbx"
	masterPassword := "supersecret"

	// Read
	file, err := os.Open(filename)
	if err != nil {
		log.Printf("Failed opening file: %+v", err)
		os.Exit(1)
	}

	// Initialize Keepass DB struct
	db := gokeepasslib.NewDatabase()
	// Set credentials
	db.Credentials = gokeepasslib.NewPasswordCredentials(masterPassword)
	// Decode file into DB struct
	err = gokeepasslib.NewDecoder(file).Decode(db)
	if err != nil {
		log.Printf("Decoding file: %+v", err)
		os.Exit(1)
	}

	// close the file again as it is not needed anymore after decode
	file.Close()

	// Unlock protected entries (stream cipher) to access entries and passwords
	db.UnlockProtectedEntries()
	entry := db.Content.Root.Groups[0].Groups[0].Entries[0]
	// Print entry to check password
	fmt.Println(entry.GetTitle())
	fmt.Println(entry.GetContent("Password"))

	// Add a new subgroup to root/groups/0 with an entry
	createSubGroups(&db.Content.Root.Groups[0])

	// Lock entries using stream cipher to prepare the data for writing
	db.LockProtectedEntries()

	// Create a new file to write to
	writeFile, err := os.Create(targetFilename)
	if err != nil {
		log.Printf("Failed to overwrite existing file: %v")
		os.Exit(1)
	}
	// and encode the database it into the file
	keepassEncoder := gokeepasslib.NewEncoder(writeFile)
	if err := keepassEncoder.Encode(db); err != nil {
		log.Printf("Failed to encode data: %v")
		os.Exit(1)
	}
	writeFile.Close()

	// Check that read was ok
	file2, err := os.Open(targetFilename)
	if err != nil {
		log.Printf("Failed opening file: %+v", err)
		os.Exit(1)
	}
	defer file2.Close()

	db2 := gokeepasslib.NewDatabase()
	db2.Credentials = gokeepasslib.NewPasswordCredentials(masterPassword)
	err = gokeepasslib.NewDecoder(file2).Decode(db2)
	if err != nil {
		log.Printf("Decoding file: %+v", err)
		os.Exit(1)
	}
	db2.UnlockProtectedEntries()
	entry2 := db2.Content.Root.Groups[0].Groups[1].Entries[0]
	fmt.Println(entry2.GetTitle())
	fmt.Println(entry2.GetContent("Password"))
}
```
Note that if you replace `targetFilename` with `filename`, you are actually overwriting the original file, if that is your intention

**Comment by MarErm27** [comment]
Hello! Merry Christmas and Happy New Year!
