### ISSUE TITLE
Time parsing simplification

### ISSUE THREAD

**Issue by Footmau** [tobischo/gokeepasslib#62]
Here is my suggestion how to improve time wrapper: https://github.com/Footmau/gokeepasslib/commit/e8ea5975ed480a308a7e47b2b9c90d69648256bf

I would like to make pull request but didn't found convenient way how to do it for single commit of my fork.

**Comment by tobischo** [comment]
You could create a branch from my current master and cherry pick this commit on top of the branch and then create a merge request between this branch and the current master.

**Comment by tobischo** [comment]
Since `time.Unix()` has the number of seconds since 1970 I am not sure that this solution will work though:
https://play.golang.org/p/FCVeeaEvBnG

**Comment by Footmau** [comment]
Should work as well, I already checked in with my app.
Negative values is ok.

**Comment by Footmau** [comment]
I verified implementation here https://play.golang.org/p/UPnMB8da2aR
Results of old and new code are identical.

**Comment by tobischo** [comment]
Thank you

I am still curious about the why and haven't had time to check that out in detail

**Comment by tobischo** [comment]
Ah, yeah, kind of makes sense.
Since `time.Unix()` can be negative, it will just hold the negative offset to `1970-01-01`.
So substracting it will actually just increase the value accordingly.
Since `0001-01-01` is the negative value that is defined, any time value given should be above that.
Even if the unix value is negative, it will have an even more negative value substracted, resulting in a positive value.

**Comment by tobischo** [comment]
Merged, added a comment so that the next person comming across this (so me in a few weeks) does not wonder about the merrits of this solution.
Also released it as v3.0.5
