### ISSUE TITLE
v2 or v3 from where??

### ISSUE THREAD

**Issue by pepa65** [tobischo/gokeepasslib#64]
I'm not getting where you're getting the v2 or v3 from, or is that just a snapshot of this repo and copying it over to a subdirectory of a project, like in `kp2`? How about github.com/Raggaer/gokpcli where `github.com/tobischo/gokeepasslib/v2` is an import, where is that coming from??

**Comment by tobischo** [comment]
Since go 1.11 golang introduced 'modules' where previously there were only packages.
Modules allow for semantic versioning for packages. Since golang uniquely identifies an import through its import path, they decided to basically add virtual import paths.

For more on modules check out https://blog.golang.org/using-go-modules
There are also descriptions about it in the wiki in the golang repo here on github.

The reasoning for going with this approach in golang over something like other languages where the package name basically stays constant and you can have only 1 version of a package/egg/gem as a dependency was to a) avoid having to fight with dependencies of dependencies that have different major version and b) allows to migrate step by step in a very large code base, without having to replace it everywhere at once, which was a concern in googles mono repo.

Now when a package uses modules, there is a go.mod file somewhere along the import path. In this case it is in the root directory https://github.com/tobischo/gokeepasslib/blob/ca8166405210bcfc6d8afd9c5001d3e48fca0115/go.mod#L1

Here it is defined as github.com/tobischo/gokeepasslib/v3
And you can find the corresponding version tags in the repo for minor and patch versioning.

Let me know if this clears thing up

**Comment by tobischo** [comment]
Regarding kp2: it uses vendoring which does copy the dependencies into the /vendor directory, which also has the advantage that I or anyone loading it never have to worry about whether the dependent package is still available.
In order to address this, golang introduced module proxies in go 1.13 (I think), however I mostly prefer the vendoring approach

**Comment by pepa65** [comment]
Thank you for your extensive explanation, very helpful! I'm going to read up on your links.
So in case of `Raggaer/gokpcli` where `v2` is imported, does it go back into the git history of this repo and then find the latest v2.* tag? Like `v2.1.3` in this case? And does importing `v3` mean that `v3.0.5` or later is used?? Or does it go back in the git history of `go.mod` and find the latest reference to `github.com/tobischo/gokeepasslib/v2`?

**Comment by tobischo** [comment]
It actually checks out the go.sum file and would take 2.0.1:

https://github.com/Raggaer/gokpcli/blob/afce16b291d43f09d7579456fdd69189cbaa1883/go.sum#L11

**Comment by pepa65** [comment]
That makes perfect sense, of course!
