### ISSUE TITLE
Data at the root level is invalid

### ISSUE THREAD

**Issue by Footmau** [tobischo/gokeepasslib#65]
![image](https://user-images.githubusercontent.com/5335629/81727611-8752c380-9489-11ea-9ee2-bbc68c9922e0.png)

Hello @tobischo, I just received this bug from user, who tried to open database saved with my application.

My code is looks like:
```
	if err := tmpDB.LockProtectedEntries(); err != nil {
		return nil
	}

	var data bytes.Buffer
	keepassEncoder := gokeepasslib.NewEncoder(&data)

	if err := keepassEncoder.Encode(tmpDB); err != nil {
		return nil
	}

	return data.Bytes()
```
Could you, please, quickly check if this code is correct. I'm as C++ developer not sure that I can return value of local variable and it will be successfully copied to return value. I tried to google, but didn't found clear answer. Thanks!

**Comment by tobischo** [comment]
Well, your error handling does look suspicious.
Can you show me the code that is calling this code?
I assume that the calling code would specifically check for a nil pointer? Otherwise you might have ignored an error here and just returned nothing

Slices are pointers to arrays, so data.Bytes() is returning a pointer to that.
The value that will be copied here will be that pointer, but not the data it points to. Not sure if that is an issue for your use case. I would assume that you only write the bytes into a file and then leave it at that.

**Comment by tobischo** [comment]
Is the user still able to open the file using your application?
Which state of gokeepasslib are you using?

**Comment by Footmau** [comment]
Yes user able to open this file with my application.
I used gomobile to generate JNI libraries that call my Go methods from Android Kotlin code. Of course it checks if returned value is null.
Also line 66879 means that significant part of database already was successfully read and kind of unexpected end of XML data has place.

**Comment by tobischo** [comment]
Ok, good.
Reading up more onto the error I also stumbled across the C# `Data at the root level is invalid` part.
So the encryption/decryption part was successful.
If it can still be opened with your application, then that means that it is not completely invalid XML, but there is an incompatibility between the XML gokeepasslib generated and the XML that C#/Keepass2 can read.

Therefore it would be great to know what the user changed in his file recently and which specific version of gokeepasslib is used in the app version the user has installed

**Comment by Footmau** [comment]
Oh, it is my fork of your library, that also supports custom icons.
Also it's possible that I incorrectly initialized some of entry properties in my code as it was with incorrect data format in recent issue (XML error was here on KeePass side).

I'll try to reproduce the issue, because user can not say exactly after which changes this problem appeared.

**Comment by Footmau** [comment]
I found this [article](https://medium.com/@lestrrat/dont-reuse-that-byte-buffer-6380ff83940f) that says it's better to copy bytes.Buffer.Bytes() before usage.

Not sure if it could lead to the problem, but I'll fix it in my code. Probably if kdbx file will be just truncated, it will be detected while hash check? I'll try to reproduce incomplete file copy implicitly.

**Comment by tobischo** [comment]
The article is about re-using the buffer.
The buffer definition is basically a `byte` slice (`[]byte`) with some meta information.
https://golang.org/src/bytes/buffer.go?s=492:717#L10

A call `.Bytes()` just returns a reference to that
https://golang.org/src/bytes/buffer.go?s=2118:2149#L44

so for cases where you do not want to initialize a new buffer and reuse it, you should copy it.
as far as I understand your code, that should not be a problem, because every time the save function is called, a new bytes buffer is initialized in `data`.

It shouldn't get to the XML part on decrypt if the data was truncated.
You should be able to test that by generating a large keepass file though so that it covers multiple encryption block. If that is in fact the issue, it should be deterministic.

**Comment by Footmau** [comment]
I understood that `.Bytes()` returns reference.
But since right after that the function scope will be closed, the local variable `var data bytes.Buffer` could became invalid and then bytes will invalid too.

Or I just do not understand how Go memory management works.

**Comment by tobischo** [comment]
Since I have not worked with JNI from go I cannot speak to how the memory is shared there exactly.

Under normal circumstances:
go allocates anything where it does not know the size or the longevity up front (which is generally the case for slices) on the heap. The value stored on the stack is the reference, which will be returned. The variable `data` will become invalid and the buffer therefore will not have a reference to the byte slice anymore. The returned value is a reference and the earliest anything is getting removed would be the next garbage collection run, but that would only be the case if there is no reference to it anymore at all.

If you copy the `bytes`, you just create a different location in memory for which you return the reference from your function which would have the same behaviour: memory on the heap and an address returned from the function

**Comment by Footmau** [comment]
Can not reproduce.
