### ISSUE TITLE
README Code Bug

### ISSUE THREAD

**Issue by LamaKami** [tobischo/gokeepasslib#73]
Hi, I noticed that in the RADME the following line doesnt work 

entry := db.Content.Root.Groups[0].Groups[0].Entries[0]

I could fix it with removing one of the Groups:

entry := db.Content.Root.Groups[0].Entries[0]

**Comment by tobischo** [comment]
HI @LamaKami 

the example is the same as in https://github.com/tobischo/gokeepasslib/blob/master/examples/example.go

Executing it works fine.

Which example keepass file are you using?

**Comment by LamaKami** [comment]
Thanks for your reply. I created a KDBX 4.0 File with KeePassXC and I'm getting the Error Message: panic: runtime error: index out of range [0] with length 0, when i have both Groups in `entry := db.Content.Root.Groups[0].Groups[0].Entries[0]`

**Comment by tobischo** [comment]
The example does not aim to be matching to the KeepassXC created file but to the file you can find in examples.

My assumption would be that it is to be expected, that a different file might have different groups and entries.

There is no way I can make that valid for all other tools since I do not know how all are initializing a fresh file or how someone else might have deleted all entries from the higher level group.

Therefore the most I would do is adapt the description to make it clear that the group/entry access part is not intended to be match every possible file.

**Comment by tobischo** [comment]
If you would like to have safe access without a panic for your file, the correct way would be to check whether the slice even has the required length for the index to be there.

For the purposes of *reading and decrypting* the file, which the example aims to highlight, the group/entry access is only there to provide slightly more guidance, but not the most important bit.

**Comment by LamaKami** [comment]
I cloned the repo, and im still getting the same error if I have two Groups. I also have to remove the /v3 in the import to get it work

**Comment by tobischo** [comment]
If you run `go run example.go` in the `examples` directory, you shouldn't have any issues.

The issue with `/v3` is something that probably happens because you are not using go modules https://go.dev/blog/using-go-modules

**Comment by LamaKami** [comment]
I just wanted to let you know that I and maybe some other users of your package could encounter the problem. That they maybe think it's buggy and than don't want to use the library and that would be a great pity :)

**Comment by tobischo** [comment]
I appreciate you pointing it out. 😃 
I added a comment on it trying to point out that different keepass files might not behave the same way.

Maybe to also provide some context from my side:

It seemed like you were genuinely confused by that, rather than you trying to point out that it was not obvious to you that this is something to think about
