### ISSUE TITLE
Incorrect new binary write

### ISSUE THREAD

**Issue by Footmau** [tobischo/gokeepasslib#78]
I'm trying to implement possibility to add attachments.
After I add a binary using `Binaries.Add(data)` it works fine, I can successfully read it.

But after lock, write, read and unlock database the new binary is like truncated. There is correct data, but it is not complete.

I'm investigating the issue, maybe will write a test, but can not say how much time it will take.

**Comment by tobischo** [comment]
So you can call `.Add` and when calling `.GetContent` immediately afterwards it returns the correct data, but when encoding and decoding the data in between, it cut of parts of it and you only get the first X bytes when calling `GetContent` again?

What is the size that you tried to write and what is the size that you received on read?

**Comment by Footmau** [comment]
- Exactly.
- For example, 1496484 and 1493775 bytes.

If add it with other application, then it opens correctly. That's why I think there is something wrong with write.

**Comment by tobischo** [comment]
You mean adding the attachment with e.g. keepass2 and then reading it with gokeepasslib works fine?

**Comment by Footmau** [comment]
Yes.

**Comment by Footmau** [comment]
Modified the binary test to reproduces the issue, but it works fine. Continue investigation in my app, may be related to incorrect usage of gokeepasslib.

**Comment by Footmau** [comment]
Unfortunately I reproduced the issue in test:
```
package gokeepasslib

import (
	"bytes"
	"math/rand"
	"testing"
)

// Tests that binaries can set and get content correctly compressed or uncompressed
func TestBinary(t *testing.T) {
	db := NewDatabase(WithDatabaseKDBXVersion4())

	randomData := make([]byte, 1024*1024)
	rand.Read(randomData)
	binary := db.Content.InnerHeader.Binaries.Add(randomData)

	db.LockProtectedEntries()
	var buffer bytes.Buffer
	encoder := NewEncoder(&buffer)
	encoder.Encode(db)
	db = NewDatabase(WithDatabaseKDBXVersion4())
	decoder := NewDecoder(bytes.NewReader(buffer.Bytes()))
	decoder.Decode(db)
	db.UnlockProtectedEntries()

	found := db.Content.InnerHeader.Binaries.Find(binary.ID)
	if data, _ := found.GetContentBytes(); string(data) != string(randomData) {
		t.Log(len(data))
		t.Log(len(randomData))
		t.Fatalf("Binary content from Find is inncorrect.")
	}
}
```

Output:
```
--- FAIL: TestBinary (0.11s)
    binary_test.go:28: 1048917
    binary_test.go:29: 1048576
    binary_test.go:30: Binary content from Find is inncorrect.
FAIL
exit status 1
FAIL    github.com/tobischo/gokeepasslib/v3     0.108s
```

If comment out the encode and decode part test passes, so there is no bug in lock and unlock functionality.

**Comment by tobischo** [comment]
Fortunately you reproduced the issue in a test

At least we now know that it is definitely gokeepasslib, so that we can investigate further and fix it

**Comment by tobischo** [comment]
At least one part of the reason this does not work as intended is that the KDBXv3.1 and KDBXv4 handling is not happening correctly.

`Binaries.Add` has no reference about whether it is KDBXv3.1 or KDBXv4.

There it always sets the compressed flag to `true` when adding a new `Binary`.
The easiest, not-completely API breaking way I can see here is to allow passing a call option to `Add` with which this can be controlled.
That is not particularly convenient though, because it moves the burden of knowing to the developer - not a particularly great developer experience.

During `Find`, the `Compressed` flag is `false`, which causes it not to be properly de-compressed.
If you comment out the `gzip` compression on `SetContent` you get to:
```
    binary_test.go:69: Received: 1048578
    binary_test.go:70: Expexted: 1048576
```

The 2 bytes in difference appear to be coming from the base64 encoding, which is also not supposed to be applied for KDBXv4.

If you also comment out the Base64 encoding/decoding you get to matching data.
When using `RawStdEncoding` instead of `StdEncoding` you alsoo get matching byte sizes, even if it was not supposed to be applied for KDBXv4

**Comment by Footmau** [comment]
Can we introduce an AddBinary method to database interface? So client do not need to remind every time which kdbx version it is and where binaries field is located since kdbx4 and kdbx3 binaries are in different places.

Also it would be great to have a getter of binaries in database interface.

**Comment by tobischo** [comment]
Yes, that would make sense - the same would make sense for find I suppose

**Comment by tobischo** [comment]
Sure, right now the way to remove it would be to update all binary references as discussed in the MR - or to just leave it in and just remove the binary reference
