### ISSUE TITLE
Incorrect key file processing

### ISSUE THREAD

**Issue by Footmau** [tobischo/gokeepasslib#82]
Create database with any **not** generated key file (not standard xml key file).
Try to open it with gokeepasslib

Expected:
Database opens successfully

Actual result:
Error "Wrong password? HMAC-SHA256 of header mismatching"
[Archive.zip](https://github.com/tobischo/gokeepasslib/files/8901511/Archive.zip) - Password "123" + key file.

**Comment by tobischo** [comment]
I think I need a bit more of a step by step instruction of what you did and what happened.

Where did the key file come from? (Since it is non standard)

Does it open successfully in that combination on Keepass2?

And the issue is that it does not open successfully on gokeepasslib?

Or did you create it using gokeepasslib and tried to open it with Keepass2 and got the error there?

**Comment by tobischo** [comment]
Ok, so the key you are passing in just contains
```
import

```

A key regularly generated by Keepass2 would have some sort of XML format 🤔 

Based on the key file version (1.00 or 2.0) the format and the way it would need to be parsed is different

That means, original keepass has different modes:
1. plain file without anything added to it
2. key file version 1
3. key file version 2

The general support for key files is not great and I have actually not used it beyond a simple "does this work for this standard case when I click through it"

**Comment by tobischo** [comment]
In order to properly support it, we'd have to extend https://github.com/tobischo/gokeepasslib/blob/b155c20c2a7744e6ec999bfa42874a8919893ec1/credentials.go#L151

As far as I understand it from a preliminary glance at KeePass 2.51.1 source code:
- `KeePassLib/Keys/KcpKeyFile.cs#LoadKeyFile` gets the file content
- It first attempts to parse it as XML and if that works it aborts
- It returns the file data directly as key if it is 32 byte
- It tries to load it as a hex file if the file data is 64 byte and returns if successful
- It just hashes the entire file content as SHA256

For your example I would assume that the last case applied

The bits of this that are current support are:
- Load the full file content
- Check if it is XML by checking for the regexp pattern: https://github.com/tobischo/gokeepasslib/blob/b155c20c2a7744e6ec999bfa42874a8919893ec1/credentials.go#L152
  - It tries the base64 decoding, so that would be key file version 1 https://github.com/tobischo/gokeepasslib/blob/b155c20c2a7744e6ec999bfa42874a8919893ec1/credentials.go#L154
- It checks if the length is less than 32 byte https://github.com/tobischo/gokeepasslib/blob/b155c20c2a7744e6ec999bfa42874a8919893ec1/credentials.go#L160 and just returns it - this would actually not be and would need to be adapted
- Otherwise it returns the first 32 bytes of the content - not great really

**Comment by tobischo** [comment]
Added a basic version in #83 with which I managed to open your file.

Definitely needs more polishing though before I would want to merge it - and verify that it works with XML files

**Comment by Footmau** [comment]
> The bits of this that are current support are

Looks much more tricky then I expected. Thank you for your investigation. For sure this should be covered with various tests, I'll look at the commit.

**Comment by Footmau** [comment]
[New database.zip](https://github.com/tobischo/gokeepasslib/files/8935729/New.database.zip)
This combination doesn't opens with gokeepasslib (no password).

**Comment by tobischo** [comment]
Adjusted accordingly, going to merge it and release it

**Comment by tobischo** [comment]
Releaves as v3.4.1
