### ISSUE TITLE
Remove deprecated dependencies

### ISSUE THREAD

**Issue by kgadams** [tobischo/gokeepasslib#98]
Would it be possible to migrate away from https://github.com/aead/argon2 (to golang.org/x/crypto/argon2) and away from https://github.com/aead/chacha20 (to golang.org/x/crypto/chacha20)?

Both projects are archived, the author recommends to migrate to the official packages.

**Comment by tobischo** [comment]
keepass2 is using modes on argon2, which at least back then were not directly usable from golang.org/x/crypto/argon2.
Specifically this part is provided by [github.com/aead/argon2](https://github.com/aead/argon2)
> This repository also exports Argon2d and Argon2id

The "problem" here used to be that there are some somewhat opinionated people on the team maintaining these packages.
While I agree with the general sentiment of not allowing people to use crypto modes that are insecure, it always depends on the context and (unfortunately) for keepass2 the decision was made to use modes that are considered insecure in a context where you do not have the file stored on your filesystem.

So that resulted in having to use a fork:
https://github.com/tobischo/gokeepasslib/blob/c2b92861ca3bda1499d64974f777fc13e60a5f16/credentials.go#L59

So the options are: convince the maintainers to support the required modes or create yet another fork to have a more up to date version of this

**Comment by tobischo** [comment]
For chacha20 I'd have to check the specifics, but I believe it was something similar

Beyond the technical requirements I don't see any issue in migrating to the official version. If you want, you can provide a pull request with a working replacement. Otherwise I can take a look when I have some time

**Comment by kgadams** [comment]
Hi Tobias, the chacha20 dependency is changed with #99. It passes all unit tests.
I'll take a look at argon2 next.

**Comment by tobischo** [comment]
Awesome, thank you
I don't suppose you tested opening a corresponding file with keepass2? 😄

**Comment by kgadams** [comment]
No, I did not :-/

**Comment by kgadams** [comment]
Ok, done now. I can open a database created with a go program with KeePassXC on my Mac.

**Comment by kgadams** [comment]
I read up on argon2d in https://github.com/golang/go/issues/23602 and unfortunately, it looks unlikely that they will export this.

**Comment by tobischo** [comment]
In that case the options are to stick with the current fork or to create another one which can be kept more up to date 😅

**Comment by kgadams** [comment]
You wouldn't feel like forking the `x/crypto/argon2` into an internal dependency here by any chance?
And occasionally updating it of course :-D
Or should we create another issue in the standard library and try to get them to reconsider?

**Comment by tobischo** [comment]
I was thinking of making it a separate repo so that I could update one without having to have a release for the other necessarily. Go would be able to pick the latest unless it is a major update anyway.

**Comment by kgadams** [comment]
That sounds great. And yes, of course it is better to have a separate repo. Bad thinking on my part.

**Comment by kgadams** [comment]
Thanks a bunch. This is really great!
I would probably have mirrored the version number of `x/crypto` for your argon2 fork, but the main thing is to use a maintained crypto library.
Now lets just hope that they will not intentionally cripple the standard implementation to completely remove the `argon2d` support...
